app_home:
    resource: "@AppBundle/Resources/config/routing.yml"

fos_user:
    resource: "@UserBundle/Resources/config/routing.yml"

captcha_routing:
    resource: "@CaptchaBundle/Resources/config/routing.yml"