app_home:
    resource: "@AppBundle/Resources/config/routing.yml"

fos_user:
    resource: "@UserBundle/Resources/config/routing.yml"

app_payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
