services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    fiche_bundle.listener.fiche:
        class: FicheBundle\EventListener\FicheListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@twig'
            - '@mailer'
        tags:
            - { name: kernel.event_listener, event: fiche.created.notif, method: onFicheCreatedNotif }
            - { name: kernel.event_listener, event: fiche.created.mail, method: onFicheCreatedMail }

    app.role_validator:
        class: AppBundle\Validator\RoleValidator
        public: true

    app.send_mail:
        class: AppBundle\Mailer\SendMail
        public: true
        arguments:
            - '@mailer'
            - '@twig'

    fiche_bundle.factory:
        class: FicheBundle\Factory\EntityFactory
        public: true
        arguments:
            - '%max_filesize%'
            - '%ressource_dir%'
            - '@security.token_storage'

    groupe_bundle.manager.groupe:
        class: GroupeBundle\Manager\GroupeManager
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'

    fiche_bundle.manager.favoris:
        class: FicheBundle\Manager\FavorisManager
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'

    app.uploader:
        class: AppBundle\Uploader\Uploader
        public: true

    app.twig.convert_bytes_extension:
        class: UserBundle\TwigExtension\ConvertBytesExtension
        tags:
            - { name: twig.extension }