fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_profil:
    path:      /profil
    defaults:
        _controller: UserBundle:Profil:index

fos_user_profil_edit:
    path:      /profil/edit
    defaults:
        _controller: UserBundle:Profil:edit

fos_user_profil_delete:
    path:      /profil/delete
    defaults:
        _controller: UserBundle:Profil:delete