app_dashboard_infinite_scroll:
    path:      /dashboard_load_more/{offset}
    defaults:
        { _controller: AppBundle:Default:dashboardInfiniteScroll, offset: null }
    condition: "request.isXmlHttpRequest()"

# --------- NOTIFICATION ----------- #
app_notification:
    path:      /groupe{groupeId}/event
    defaults:
        _controller: AppBundle:Notification:index
    requirements:
        groupeId: \d+

app_all_notif:
    path:      /notifications
    defaults:
        _controller: AppBundle:Notification:all

app_notif:
    path:      /notif
    defaults:
        _controller: AppBundle:Notification:ajaxShowNotif
    condition: "request.isXmlHttpRequest()"

app_notif_active:
    path:      /notif-active
    defaults:
        _controller: AppBundle:Notification:ajaxActivated
    condition: "request.isXmlHttpRequest()"

app_all_notif_active:
    path:      /notif-all-active
    defaults:
        _controller: AppBundle:Notification:ajaxAllActivated
    condition: "request.isXmlHttpRequest()"

# --------- SEARCH ----------- #
app_search:
    path:       /search
    defaults:
        _controller: AppBundle:Search:index
    methods: GET

# --------- LOGOUT ----------- #
logout:
    path: /logout