app_home:
    path:      /
    defaults:
        _controller: AppBundle:Default:index

# ----------- GROUPE ----------- #
app_groupe:
    path:      /groupe{id_groupe}/{page}
    defaults:
        _controller: AppBundle:Groupe:index
        page:        1
    requirements:
        id_groupe: \d+
        page: \d*

app_groupe_edit:
    path:      /groupe{id_groupe}/edit
    defaults:
        _controller: AppBundle:Groupe:edit
    requirements:
        id_groupe: \d+

app_groupe_delete:
    path:      /groupe{id_groupe}/delete
    defaults:
        _controller: AppBundle:Groupe:delete
    requirements:
        id_groupe: \d+

app_groupe_add:
    path:      /groupe/add
    defaults:
        _controller: AppBundle:Groupe:add
    requirements:
        id_groupe: \d+

# --------- FICHE ----------- #
app_fiche:
    path:      /groupe{id_groupe}/fiche{id_fiche}
    defaults:
        _controller: AppBundle:Fiche:index
    requirements:
        id_fiche: \d+
        id_groupe: \d+

app_fiche_edit:
    path:      /groupe{id_groupe}/fiche{id_fiche}/edit
    defaults:
        _controller: AppBundle:Fiche:edit
    requirements:
        id_fiche: \d+
        id_groupe: \d+

app_fiche_delete:
    path:      /groupe{id_groupe}/fiche{id_fiche}/delete
    defaults:
        _controller: AppBundle:Fiche:delete
    requirements:
        id_fiche: \d+
        id_groupe: \d+

app_fiche_add:
    path:      /groupe{id_groupe}/fiche/add
    defaults:
        _controller: AppBundle:Fiche:add
    requirements:
        id_groupe: \d+

# --------- MES FICHES ----------- #
app_mes_fiches:
    path:   /mes-fiches
    defaults:
        _controller: AppBundle:MesFiches:index

# --------- RESSOURCES ----------- #
app_ressource_add:
    path:      /groupe{groupeId}/fiche{ficheId}/add-ressource
    defaults:
        _controller: AppBundle:Ressource:add
    requirements:
        groupeId: \d+
        ficheId: \d+

app_ressource_view:
    path:     /groupe{groupeId}/fiche{ficheId}/view/ressource
    defaults:
        _controller: AppBundle:Ressource:view
    requirements:
        groupeId: \d+
        ficheId: \d+

app_ressource_dl:
    path:     /groupe{groupeId}/fiche{ficheId}/dl/{fileName}
    defaults:
        _controller: AppBundle:Ressource:download
    requirements:
        groupeId: \d+
        ficheId: \d+

app_ressource_delete:
    path:     /groupe{groupeId}/fiche{ficheId}/delete-ressource
    defaults:
        _controller: AppBundle:Ressource:delete
    requirements:
        groupeId: \d+
        ficheId: \d+

# --------- MEMBRE ---------- #
app_membre:
    path:      /groupe{id_groupe}/membre
    defaults:
        _controller: AppBundle:Membre:index
    requirements:
        id_groupe: \d+

# --------- FAVORIS ---------- #
app_favoris:
    path:      /favoris
    defaults:
        _controller: AppBundle:Favoris:index

app_favoris_action:
    path:      /favoris-add
    defaults:
        _controller: AppBundle:Favoris:ajaxAdd

# --------- INVITE ----------- #
app_invite:
    path:      /invite
    defaults:
        _controller: AppBundle:Invite:index

app_invite_add:
    path:      /groupe{groupeId}/invite/add
    defaults:
        _controller: AppBundle:Invite:add
    requirements:
        groupeId: \d+

app_invite_confirm:
    path:   /invite-confirm
    defaults:
        _controller: AppBundle:Invite:inviteConfirm

# --------- NOTIFICATION ----------- #
app_notification:
    path:      /groupe{groupeId}/event
    defaults:
        _controller: AppBundle:Notification:index
    requirements:
        groupeId: \d+

app_all_notif:
    path:      /notifications
    defaults:
        _controller: AppBundle:Notification:all

app_notif_active:
    path:      /notif-active
    defaults:
        _controller: AppBundle:Notification:ajaxActivated

app_all_notif_active:
    path:      /notif-all-active
    defaults:
        _controller: AppBundle:Notification:ajaxAllActivated

# --------- PARAMETRE ----------- #
app_parametre:
    path:      /parametre
    defaults:
        _controller: AppBundle:Parametre:index

logout:
    path: /logout